# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArctileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('viewCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePerDayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('perDayViews', models.TextField()),
            ],
        ),
    ]
