# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikistats', '0002_auto_20170731_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiArticles',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
